apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "treetracker-solr"
  namespace: "webmap"
  labels:
    app: "treetracker-solr"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "treetracker-solr"
  template:
    metadata:
      labels:
        app: "treetracker-solr"
    spec:
      containers:
      - name: "treetracker-solr"
        image: solr:8
        env:
          - name: SOLR_HEAP
            value: 300m
          - name: SOLR_JAVA_MEM
            value: -Xms300m -Xmx300m
