# k8s yaml to create a workspace: persistent volume, persistent volume claim, development pod, there are two pods:
# 1. ubuntu pod with a persistent volume mounted at /mnt/data, as command line editor and server runner e.g. next
# 2. kasm pod with a persistent volume mounted at /mnt/data, to offer desktop

---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority
value: 1000000
globalDefault: false
description: "This priority class is for important pods."

---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: highest-priority
value: 1000001
globalDefault: false
description: "This priority class is for most important pods."


---
# nfs server
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: workspace
  name: nfs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-server
  template:
    metadata:
      labels:
        app: nfs-server
    spec:
      priorityClassName: highest-priority
      nodeSelector:
        mylabel: core
      containers:
      - name: nfs-server
        image: k8s.gcr.io/volume-nfs:0.8
        ports:
        - name: nfs
          containerPort: 2049
        - name: mountd
          containerPort: 20048
        - name: rpcbind
          containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - name: storage
            mountPath: /exports
      volumes:
        - name: storage
          hostPath:
            path: /data/nfs # store all data in "/data/nfs" directory of the node where it is running
            type: DirectoryOrCreate # if the directory does not exist then create it

---
apiVersion: v1
kind: Service
metadata:
  name: nfs-service
  namespace: workspace
spec:
  ports:
  - name: nfs
    port: 2049
  - name: mountd
    port: 20048
  - name: rpcbind
    port: 111
  selector:
    app: nfs-server # must match with the label of NFS pod

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: workspace
  name: editor
spec:
  replicas: 1
  # select node by label
  selector:
    matchLabels:
      app: editor
  template:
    metadata:
      labels:
        app: editor
    spec:
      nodeSelector:
        mylabel: core
      containers:
      - name: editor-container
        image: dadiorchen/editor:1.0
        resources:
          requests:
            memory: "1000Mi"
          limits:
            memory: "4000Mi"
        command: 
          - /bin/bash
          - -c
          - -l
          - |
            apt install -y tmux unzip sudo
            sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
              https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
            mkdir -p /root/.config
            ln -s /mnt/data/config-nvim /root/.config/nvim
            nvim +PlugInstall +qall
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash && \
            source /root/.nvm/nvm.sh && \
            npm install -g typescript-language-server
            # install aws cli
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
            unzip awscliv2.zip && \
            sudo ./aws/install

            tail -f /dev/null
        env:
        - name: NODE_OPTIONS
          value: "--max-old-space-size=2048"
        volumeMounts:
        - mountPath: "/mnt/data"
          name: workspace-volume
      volumes:
      - name: workspace-volume
        nfs:
          #server: "nfs-service.workspace.svc.cluster.local"
          server: "10.245.18.37"
          path: "/nfs-direct" # "nfs-direct" folder must exist inside "/exports" directory of NFS server
      priorityClassName: high-priority

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: workspace
  name: desktop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: desktop
  template:
    metadata:
      labels:
        app: desktop
    spec:
      nodeSelector:
        mylabel: ext
      containers:
      - name: desktop-container
        image: dadiorchen/desktop:1.0
        resources:
          requests:
            memory: "2000Mi"
          limits:
            memory: "8000Mi"
        command: 
          - /bin/bash
          - --login
          - -c
          - |
            # run the startup script in the background
            export STARTUPDIR=/dockerstartup
            source /etc/profile
            source /root/.bashrc
            source /home/kasm-user/.bashrc
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash && \
            source /root/.nvm/nvm.sh && \
            nvm install 18 && \
            nvm use 18 && \
            cd /mnt/data/bluebot-saas-client/ && \
            npx cypress install && \
            /dockerstartup/kasm_default_profile.sh && \
            /dockerstartup/vnc_startup.sh && \
            /dockerstartup/kasm_startup.sh
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        # env VNC_PW=123456
        env:
        - name: VNC_PW
          value: "Cy;{C52<48aM"
        - name: NODE_OPTIONS
          value: "--max-old-space-size=1024"
        volumeMounts:
        - mountPath: "/mnt/data"
          name: workspace-volume
      volumes:
      - name: workspace-volume
        nfs:
          #server: "nfs-service.workspace.svc.cluster.local"
          server: "10.245.18.37"
          path: "/nfs-direct" # "nfs-direct" folder must exist inside "/exports" directory of NFS server

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: workspace
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      nodeSelector:
        mylabel: ext
      containers:
      - name: desktop-container
        image: dadiorchen/editor:1.0
        resources:
          requests:
            memory: "500Mi"
          limits:
            memory: "2000Mi"
        #command to run npm start
        command: 
          - /bin/bash
          - -c
          - |
            source /root/.nvm/nvm.sh
            cd /mnt/data/bluebot-saas-client/
            #IS_CYPRESS_TEST=true IS_CYPRESS_INT_TEST=true npm run dev -- --experimental-https
            npm run dev -- --experimental-https
        env:
        - name: NODE_OPTIONS
          value: "--max-old-space-size=2048"
        volumeMounts:
        - mountPath: "/mnt/data"
          name: workspace-volume
      volumes:
      - name: workspace-volume
        nfs:
          #server: "nfs-service.workspace.svc.cluster.local"
          server: "10.245.18.37"
          path: "/nfs-direct" # "nfs-direct" folder must exist inside "/exports" directory of NFS server

---
apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: workspace
spec:
  ports:
    - port: 3001
      targetPort: 3001
  selector:
    app: server



---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: workspace
  name: editor-aws
spec:
  replicas: 0
  # select node by label
  selector:
    matchLabels:
      app: editor-aws
  template:
    metadata:
      labels:
        app: editor-aws
    spec:
      nodeSelector:
        mylabel: core
      containers:
      - name: editor-container
        image: dadiorchen/editor:1.0
        command: 
          - /bin/bash
          - -c
          - -l
          - |
            apt install -y tmux sudo unzip
            sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
              https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
            mkdir -p /root/.config
            ln -s /mnt/data/config-nvim /root/.config/nvim
            nvim +PlugInstall +qall
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash && \
            source /root/.nvm/nvm.sh && \
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
            unzip awscliv2.zip && \
            sudo ./aws/install
            tail -f /dev/null
        env:
        volumeMounts:
        - mountPath: "/mnt/data"
          name: workspace-volume
      volumes:
      - name: workspace-volume
        nfs:
          #server: "nfs-service.workspace.svc.cluster.local"
          server: "10.244.28.157"
          path: "/nfs-direct" # "nfs-direct" folder must exist inside "/exports" directory of NFS server
      priorityClassName: high-priority


# postgres
---
# postgres deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: workspace
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      nodeSelector:
        mylabel: core
      containers:
        - name: postgres
          image: postgres:13
          env:
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"
          - name: POSTGRES_DB
            value: "postgres"
          - name: POSTGRES_HOST_AUTH_METHOD
            value: "trust"

---
# postgres service
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: workspace
spec:
  ports:
    - port: 5432
  selector:
    app: postgres

